<?php $this->headTitle('Blog') ?>


<h2>Blog</h2>

<p>
    <a href="<?=$this->url('post', ['action'=>'add']); ?>">
        New Post
    </a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Action</th>
    </tr>
    <?php foreach ($posts as $post): ?> 
       <tr>
        <td><?=$this->escapeHtml($post->title); ?></td>
        <td><?=$this->escapeHtml($post->content); ?></td>
        <td>
            <a href="<?=$this->url('post', ['action'=>'edit', 'id'=>$post->id]); ?>">
                Edit
            </a>

            <a href="<?=$this->url('post', ['action'=>'delete', 'id'=>$post->id]); ?>">
                Delete
            </a>
        </td>
       </tr>
    <?php endforeach ?>
</table>
        